version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production:
        update-types:
          - "minor"
          - "patch"
      development:
        dependency-type: "development"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/apps/journal"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/apps/planner"
    schedule:
      interval: "monthly"
