packages:
  - "apps/*"
  - "packages/*"
  - "scripts"

catalog:
  react: ^19.2.5
  react-dom: ^19.2.5
  react-router: ^7.14.2
  "@react-router/dev": ^7.14.2
  "@react-router/node": ^7.14.2
  "@react-router/serve": ^7.14.2
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  tailwindcss: ^4.2.4
  "@tailwindcss/vite": ^4.2.4
  typescript: ^5.8.3
  vite: ^8.0.8
  drizzle-orm: ^0.45.2
  drizzle-kit: ^0.31.10
  drizzle-postgis: ^1.1.1
  "@sentry/node": ^10.50.0
  "@sentry/react": ^10.49.0
  postgres: ^3.4.9
  "@types/node": ^22.0.0

