import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route(".well-known/trails-cool", "routes/api.well-known.trails-cool.ts"),
  route("oauth/authorize", "routes/oauth.authorize.tsx"),
  route("oauth/token", "routes/oauth.token.ts"),
  route("auth/register", "routes/auth.register.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/verify", "routes/auth.verify.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("api/auth/register", "routes/api.auth.register.ts"),
  route("api/auth/login", "routes/api.auth.login.ts"),
  route("routes", "routes/routes._index.tsx"),
  route("routes/new", "routes/routes.new.tsx"),
  route("routes/:id", "routes/routes.$id.tsx"),
  route("routes/:id/edit", "routes/routes.$id.edit.tsx"),
  route("api/routes/:id/callback", "routes/api.routes.$id.callback.ts"),
  route("api/routes/:id/edit-in-planner", "routes/api.routes.$id.edit-in-planner.ts"),
  route("api/routes/:id/gpx", "routes/api.routes.$id.gpx.ts"),
  route("activities", "routes/activities._index.tsx"),
  route("activities/new", "routes/activities.new.tsx"),
  route("activities/:id", "routes/activities.$id.tsx"),
  route("users/:username", "routes/users.$username.tsx"),
  route("settings", "routes/settings.tsx"),
  route("api/settings/profile", "routes/api.settings.profile.ts"),
  route("api/settings/email", "routes/api.settings.email.ts"),
  route("api/settings/passkey/delete", "routes/api.settings.passkey.delete.ts"),
  route("api/settings/delete-account", "routes/api.settings.delete-account.ts"),
  route("sync/import/:provider", "routes/sync.import.$provider.tsx"),
  route("api/sync/connect/:provider", "routes/api.sync.connect.$provider.ts"),
  route("api/sync/callback/:provider", "routes/api.sync.callback.$provider.ts"),
  route("api/sync/disconnect/:provider", "routes/api.sync.disconnect.$provider.ts"),
  route("api/sync/webhook/:provider", "routes/api.sync.webhook.$provider.ts"),
  route("privacy", "routes/privacy.tsx"),
] satisfies RouteConfig;
